Repository Arquisoft/lomap_en1b, pull requests merged in 2023-03, with the labels that each got.

#54 Login Interface and Home Page
  package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/About.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/Login.tsx
Labels: mandatory feature:wrench::large_blue_circle:, Waiting:sleeping:

#74 Login URLs
  webapp/src/components/Login.tsx
Labels: UI/UX:iphone::ok_woman:

#76 UI/UX Improval: Login form
  webapp/src/components/Login.tsx
Labels: enhancement:up::arrow_up:, UI/UX:iphone::ok_woman:
