Repository Arquisoft/lomap_en1b, pull requests merged in 2023-04, with the labels that each got.

#79 Navigation bar Sara Sil
  webapp/src/components/NavBar.tsx
  webapp/src/css/nav.css
  webapp/src/css/react_leaflet.css
Labels: UI/UX:iphone::ok_woman:

#85 Merge develop into ivan
  restapi/package.json
  restapi/src/builders/friendBuilder.ts
  restapi/src/builders/locationBuilder.ts
  restapi/src/repo/repository.ts
  restapi/src/routes/authenticationRouter.ts
  restapi/src/routes/friendshipsRouter.ts
  restapi/src/routes/locationsRouter.ts
  restapi/src/server.ts
  restapi/src/services/authenticationService.ts
  restapi/src/services/friendshipsService.ts
  restapi/src/services/locationsService.ts
  restapi/src/validators/friendValidator.ts
  webapp/src/App.tsx
  webapp/src/app/services/Friend.tsx
  webapp/src/app/services/Location.tsx
  webapp/src/app/store.ts
  webapp/src/components/FriendsPage/Entry.tsx
  webapp/src/components/FriendsPage/FriendsView.tsx
  webapp/src/components/Map.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/types.d.ts
Labels: UI/UX:iphone::ok_woman:, REDUX:twisted_rightwards_arrows:

#91 Design decisions point updated.
  docs/01_introduction_and_goals.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
  restapi/build/builders/friendBuilder.js
  restapi/build/builders/locationBuilder.js
  restapi/build/locationType.js
  restapi/build/podsAccess/authenticationService.js
  restapi/build/podsAccess/locationsService.js
  restapi/build/repo/db.js
  restapi/build/repo/repository.js
  restapi/build/routes/authenticationRouter.js
  restapi/build/routes/friendshipsRouter.js
  restapi/build/routes/locationsRouter.js
  restapi/build/server.js
  restapi/build/services/authenticationService.js
  restapi/build/services/friendshipsService.js
  restapi/build/services/locationsService.js
  restapi/build/validators/friendValidator.js
  restapi/build/validators/locationValidator.js
Labels: documentation:page_facing_up::pen:

#100 Review Form and Details drawer added to locations
  package-lock.json
  package.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/app/services/DisplayedLocations.tsx
  webapp/src/app/store.ts
  webapp/src/components/Map.tsx
  webapp/src/components/mapComponents/LocationReviewsView.tsx
  webapp/src/types.d.ts
Labels: mandatory feature:wrench::large_blue_circle:, UI/UX:iphone::ok_woman:

#105 Map view changes on add review form and map filter
  webapp/src/components/Map.tsx
  webapp/src/components/mapComponents/LocationReviewsView.tsx
Labels: UI/UX:iphone::ok_woman:
